
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';

export const OPEN_ADD_USER_MODAL = 'OPEN_ADD_USER_MODAL';
export const CLOSE_ADD_USER_MODAL = 'CLOSE_ADD_USER_MODAL';
